### PR TITLE
High-level protocol tunneling

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Resolves https://github.com/UAVCAN/dsdl/issues/3, supersedes https://github.com/UAVCAN/dsdl/pull/39.

This is a revised implementation of the old concept that takes into account meaningful usage scenarios and the recent improvements of the protocol.

### CODE REVIEW

**Comment by magicrub** [comment]
Looks like you've renamed it to "tunnel" but there are still references to "foreign object" in the source.

**Comment by pavel-kirienko** [comment]
Good catch! Fixed

**Comment by magicrub** [comment]
can you cherry pick this?
https://github.com/magicrub/dsdl/commit/3a0296409ec05f62f6a9bf179e716ec8d307d5a6

We have a ton of enum space, might as well throw a few protocols up there to start with.

**Comment by pavel-kirienko** [comment]
Do you have specific use cases in mind? We can add them, sure (all except `RAW` - that option doesn't make sense and it was a mistake), but that doesn't mean we should. MAVLink is a good option for tunneling, as it is largely self-describing (meaning that you don't need additional context to understand MAVLink traffic); whereas other options are a lot more low-level - they provide mere encoding format rather than a high-level data exchange protocol. Therefore I propose to push back on that; we will always be able to add additional protocols later as necessary.

**Comment by magicrub** [comment]
Nothing specific in mind. The point is to let anyone pass whatever they want. You're arbitrarily trying to restrict that. Doesn't make sense. I don't see any harm filling the enum with the top 50 protocols, whatever they are.

**Comment by pavel-kirienko** [comment]
It is true that I am intentionally trying to restrict the available options because that makes interoperability difficult.

**Pull request merged**
