### PR TITLE
Fix duplicate variable ids

### PR DESCRIPTION
**Pull request by bugobliterator**
@pavel-kirienko Sorry for breaking master! Should have checked that before requesting to to pull my PR.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Thanks for fixing this. It's a serious problem that we don't check this automatically. I should implement this check soon.

**Comment by bugobliterator** [comment]
I will try and add a travis check for this. So that this can be avoided.

**Comment by pavel-kirienko** [comment]
Awesome.

**Comment by bugobliterator** [comment]
I think simply running dsdl compiler on it should do. Do you agree.

**Comment by pavel-kirienko** [comment]
Yes, it should be enough. We have a ticket for this: https://github.com/UAVCAN/dsdl/issues/18

**Pull request merged**
