### PR TITLE
Added message 1002.MagneticFieldStrength2.uavcan

### PR DESCRIPTION
**Pull request by AlexeyBulatov**
New message based on 1001.MagneticFieldStrength with new field sensor_id, which can be used if your node has more then one sensor.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
Thanks Alexey.

Could you please briefly describe the use case that you envision for this message? Why does your application require multiple magnetometers per node? Thanks!

**Comment by AlexeyBulatov** [comment]
The proposed implementation looks like a viable solution in case several sensors need to be used on a device.
If I am not mistaken, another approach (i.e. adding a new node for magnetometer) might make parameter updating more difficult . From simple tests that I conducted it seems like adding another node also yields a bigger binary.

**Comment by pavel-kirienko** [comment]
Thanks @AlexeyBulatov. Seems like nobody have objected to this proposition in 8 days.

I suggest to declare the old message deprecated in the header comment, could you please do that, and I'll merge this ASAP.

Thanks.

**Comment by AlexeyBulatov** [comment]
Thank you @pavel-kirienko!
I have added comment about deprecated message.

**Pull request merged**
